### ISSUE TITLE
Error: Cannot find module 'react-router/lib/Location'

### ISSUE THREAD

**Issue by 0xR** [jarsbe/redux-isomorphic-example#1]
```
git clone
npm install
npm start
```

get error:

```
Error: Cannot find module 'react-router/lib/Location'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by jackcallister** [comment]
@0xR The Location lib must have moved in `1.0.0-beta4` but the docs aren't out so I've locked the react router version to `1.0.0-beta3`. Try pulling, clearing out your modules and installing again.
